# Generated by Django 5.1 on 2024-08-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_country',
            field=models.CharField(default='INDIA', max_length=100),
        ),
    ]
